/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_libmailcore_IMAPCustomCommandOperation */

#ifndef _Included_com_libmailcore_IMAPCustomCommandOperation
#define _Included_com_libmailcore_IMAPCustomCommandOperation
#ifdef __cplusplus
extern "C" {
#endif
#undef com_libmailcore_IMAPCustomCommandOperation_serialVersionUID
#define com_libmailcore_IMAPCustomCommandOperation_serialVersionUID 1LL
#ifdef __cplusplus
}
#endif
#endif
